grails-app/controllers/AuthController.groovy
import org.apache.shiro.SecurityUtils
import org.apache.shiro.authc.AuthenticationException
import org.apache.shiro.authc.UsernamePasswordToken
import org.apache.shiro.web.util.SavedRequest
import org.apache.shiro.web.util.WebUtils

class AuthController {
    def shiroSecurityManager

    def index = { redirect(action: "login", params: params) }

    def login = {
        return [username:   flash.username ?: params.username, 
                rememberMe: flash.rememberMe ?: (params.rememberMe != null), 
                targetUri:  flash.targetUri ?: params.targetUri]
    }

    def signIn = {
        def authToken = new UsernamePasswordToken(params.username, params.password as String)

        // Support for "remember me"
        if (params.rememberMe) {
            authToken.rememberMe = true
        }
        
        // If a controller redirected to this page, redirect back
        // to it. Otherwise redirect to the root URI.
        def targetUri = params.targetUri ?: "/"
        
        // Handle requests saved by Shiro filters.
        def savedRequest = WebUtils.getSavedRequest(request)
        if (savedRequest) {
            targetUri = savedRequest.requestURI - request.contextPath
            if (savedRequest.queryString) targetUri = targetUri + '?' + savedRequest.queryString
        }
        
        try{
            // Perform the actual login. An AuthenticationException
            // will be thrown if the username is unrecognised or the
            // password is incorrect.
            SecurityUtils.subject.login(authToken)

            //println "Redirecting to '${targetUri}'."
            redirect(uri: targetUri)
        }
        catch (AuthenticationException ex){
            // Authentication failed, so display the appropriate message
            // on the login page.
            log.info "Authentication failure for user '${params.username}'."
            flash.message = message(code: "login.failed")

            // Keep the username and "remember me" setting so that the
            // user doesn't have to enter them again.
            //def m = [ username: params.username ]
            flash.username = params.username
            if (params.rememberMe) {
                //m["rememberMe"] = true
                flash.rememberMe = true
            }

            // Remember the target URI too.
            if (params.targetUri) {
                //m["targetUri"] = params.targetUri
                flash.targetUri = params.targetUri
            }

            // Now redirect back to the login page.
            //redirect(action: "login", params: m)
            redirect(action: "login")
        }
    }

    def signOut = {
        // Log the user out of the application.
        SecurityUtils.subject?.logout()

        // For now, redirect back to the home page.
        redirect(uri: "/")
    }

    def unauthorized = {
        //render "You do not have permission to access this page."
        render(view: '/403', status: 403)
    }
}

grails-app/controllers/com/mublog/ApiController.groovy
package com.mublog

class ApiController {

    def index = { }
    
    def post = {
        def p = Post.get(params.id ? params.int('id') : -1)
        if (p) {
            render(contentType: "text/json") {
                [id: p.id, text: p.message, user_id: p.user.id, user: p.user.username, date: p.dateCreated.format("HH:mm, dd MMM yyyy")]
            }
        }
        else
            render(contentType: "text/json", status: 404) { error = "not found" }
    }

    def add = {
        def u = ShiroUser.findByUsernameAndPasswordHash(params.user, params.hash)
        if (u) {
            def p = new Post(message: params.text, user: u)
            if (p.save(flush: true)) {
                render(contentType: "text/json") { [id: p.id, text: p.message, user_id: p.user.id, user: p.user.username, date: p.dateCreated.format("HH:mm, dd MMM yyyy")] }
            }
            else
                render(contentType: "text/json") { error = message(code: "post.message.${p.errors.getFieldError("message").code}") }
        }
        else
            render(contentType: "text/json", status: 401) { error = "not authenticated" }
    }

    def delete = {
        def u = ShiroUser.findByUsernameAndPasswordHash(params.user, params.hash)
        if (u) {
            def p = Post.get(params.id ? params.int('id') : 0)
            if (p) {
                if (! p.subjectCanDelete(u))
                    return render(contentType: "text/json", status: 403) { error = "permission denied" }
                if (p.delete(flush: true)) 
                    render(contentType: "text/json") { status = "ok" }
                else
                    render(contentType: "text/json") { error = "can't delete" }
            }
            else
                render(contentType: "text/json", status: 404) { error = "not found" }
        }
        else
            render(contentType: "text/json", status: 401) { error = "not authenticated" }
    }

    def latest = {
        params.max = Math.min(params.max ? params.int('max') : 25, 25)
        params.offset = params.offset ? params.int('offset') : 0
        params.sort = 'dateCreated'
        params.order = 'desc'

        def ps = Post.withCriteria {
            if (params.after)
                gt('id', params.long('after'))
            firstResult(params.offset)
            maxResults(params.max)
            order(params.sort, params.order)
        }
        render(contentType: 'text/json') {
            array {
                for (p in ps) {
                    element id: p.id, text: p.message, user_id: p.user.id, user: p.user.username, date: p.dateCreated.format("HH:mm, dd MMM yyyy")
                }
            }
        }
    }

    def posted_by_user = {
        def u = ShiroUser.get(params.id ? params.int('id') : 0)
        if (u) {
            params.max = Math.min(params.max ? params.int('max') : 25, 25)
            params.offset = params.offset ? params.int('offset') : 0
            params.sort = 'dateCreated'
            params.order = 'desc'

            def ps = null
            if (params.after)
                ps = Post.findAllByUserAndIdGreaterThan(u, params.long('after'), params)
            else
                ps = Post.findAllByUser(u, params)

            render(contentType: "text/json") {
                array {
                    for (p in ps) {
                        element id: p.id, text: p.message, user_id: p.user.id, user: p.user.username, date: p.dateCreated.format("HH:mm, dd MMM yyyy")
                    }
                }
            }
        }
        else
            render(contentType: "text/json", status: 404) { error = "not found" }
    }
}

grails-app/views/layouts/main.gsp
<!doctype html>
<html lang="ru">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title><g:layoutTitle default="μBlog" /></title>
  <link rel="stylesheet" href="${resource(dir:'css',file:'bootstrap.css')}" />
  <link rel="stylesheet" href="${resource(dir:'css',file:'bootstrap-responsive.css')}" />
  <link rel="shortcut icon" href="${resource(dir:'images',file:'favicon.ico')}" type="image/x-icon" />
  <style type="text/css">
    body {
        padding-top: 60px;
    }
  </style>
  <g:javascript library="jquery-1.7.1.min" />
  <g:javascript library="bootstrap" />
  <g:javascript library="bootstrap-alert" />
  <g:javascript library="application" />
  <g:layoutHead />
  <!--[if lt IE 9]><script type="text/javascript" src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
</head>

<body>

    <div class="navbar navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container-fluid">
                <!--a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a-->
                <a class="brand" href="/">μBlog</a>
                <p class="navbar-text pull-left">Сервис микроблоггов</p>
                <!--div class="navbar-text pull-left" style='border-right:#555555 1px dotted'>&nbsp;</div-->
                <div class="nav-collapse">
                    <ul class="nav">
                        <li class="divider-vertical"></li>
                        <li><a href="/"><i class="icon-home icon-white"></i> Home</a></li>
                        <li><g:link controller="post" action="create"><i class="icon-pencil icon-white"></i> New Post</g:link></li>
                        <li><g:link controller="user" action="my"><i class="icon-user icon-white"></i> My Page</g:link></li>
                        <li class="divider-vertical"></li>
                    </ul>
                </div>
                <div class="nav-collapse pull-left">
                    <g:form controller="home" action="search" class="navbar-search" method="get">
                        <input name="q" type="text" class="span2 search-query small" placeholder="Search" />
                    </g:form>
                </div>
                <ul class="nav">
                    <li class="divider-vertical"></li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Docs<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><g:link controller="api" action="index"><i class="icon-book"></i> API</g:link></li>
                        </ul>
                    </li>
                </ul>
                <div class="nav-collapse pull-right">
                    <shiro:user>
                        <div class="navbar-text pull-left">
                            Logged in as <g:link controller="user" action="my"><shiro:principal /></g:link>
                        </div>
                        <ul class="nav">
                            <li class="divider-vertical"></li>
                            <li><g:link controller="auth" action="signOut">Log Out</g:link></li>
                        </ul>
                    </shiro:user>
                    <shiro:notUser>
                        <div class="pull-right">
                            <ul class="nav">
                                <li><g:link controller="auth" action="login">Log In</g:link></li>
                                <li><g:link controller="user" action="create">Registration</g:link></li>
                            </ul>
                        </div>
                    </shiro:notUser>
                </div>
            </div>
        </div>
    </div>

<div class="container">

    <g:if test="${flash.message}">
        <div class="alert alert-info">
            <a class="close" data-dismiss="alert">×</a>
            ${flash.message}
        </div>
    </g:if>

    <g:if test="${flash.error}">
        <div class="alert alert-error">
            <a class="close" data-dismiss="alert">×</a>
            <h4 class="alert-heading">Error!</h4>
            ${flash.error}
        </div>
    </g:if>

    <g:layoutBody />

    <hr>

    <footer>
        <p>&copy; Simple microblog 2012</p>
    </footer>
</div>

</body>
</html>

grails-app/views/layouts/main.old.gsp
<!DOCTYPE html>
<html>
    <head>
        <title><g:layoutTitle default="Grails" /></title>
        <link rel="stylesheet" href="${resource(dir:'css',file:'main.css')}" />
        <link rel="shortcut icon" href="${resource(dir:'images',file:'favicon.ico')}" type="image/x-icon" />
        <g:layoutHead />
        <g:javascript library="application" />
    </head>
    <body>
        <div id="spinner" class="spinner" style="display:none;">
            <img src="${resource(dir:'images',file:'spinner.gif')}" alt="${message(code:'spinner.alt',default:'Loading...')}" />
        </div>
        <div id="grailsLogo"><a href="http://grails.org"><img src="${resource(dir:'images',file:'grails_logo.png')}" alt="Grails" border="0" /></a></div>
        <g:layoutBody />
    </body>
</html>